## 학습목표
 1. numpy & pandas basic

* numpy 
  - 기본 array 생성

In [1]:
import numpy as np
print np.__version__
#수치해석에 매우 좋은 파이썬이지만 느리다는 치명적 단점이 있다.
#이를 해결하고자 나타난 것이 numpy. C언어로 짜여져있기 때문에 매우 빠르다.
#업데이트하려면 cygwin에서 pip install -U numpy. pip가 왜 좋은지 알수 있지! 편리하다. 
#그리고 kernel restart하면 업데이트 된거 확인할 수 있어.
#pip install --help 를 치면 pip install에 대한 도움말 볼 수 있음. -U 특히 많이 씀. upgrade

1.12.0


In [1]:
import numpy as np
print np.__version__

1.12.0


* ndarray
 - numpy의 기본 타입
 - vector, matrix를 표현
 - numpy.array([])로 생성

In [2]:
arr1 = np.array([1, 3, 4, 6])
arr2 = np.array([[0, 1, 2], [2, 4, 6],[3, 6, 9]])

print arr1, type(arr1)
print
print arr2, type(arr2)

[1 3 4 6] <type 'numpy.ndarray'>

[[0 1 2]
 [2 4 6]
 [3 6 9]] <type 'numpy.ndarray'>


In [5]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,4,6,8])
print arr1, arr2
print arr1+arr2
print arr1 * arr2

[1 2 3 4] [1 4 6 8]
[ 2  6  9 12]
[ 1  8 18 32]


* arange 
 - range()와 동일한 기능을 수행함
 - 다만 list가 아닌 
 - ndarray를 반환

In [7]:
arr3 = np.arange(1, 11)
print arr3, type(arr3)

[ 1  2  3  4  5  6  7  8  9 10] <type 'numpy.ndarray'>


In [6]:
arr3 = np.arange(1,10)
print arr3

[1 2 3 4 5 6 7 8 9]


* linspace()
 - start, end를 n개의 균일한 간격으로 분할

In [8]:
arr4 = np.linspace(0,2,4)
print arr4

[ 0.          0.66666667  1.33333333  2.        ]


In [9]:
# 0 - 2의 범위를 5등분 한다는 이야기
arr4 = np.linspace(0, 2, 5)
print arr4

[ 0.   0.5  1.   1.5  2. ]


* zeros
 - 전달된 tuple 사이즈 행렬 반환
 - 0으로 채워짐

In [15]:
print np.zeros((3, 4))
print
print np.zeros(4)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

[ 0.  0.  0.  0.]


In [10]:
print np.zeros((4,4)) #행렬 사이즈를 tuple로 전달함

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


* ones
 - 전달된 tuple 사이즈 행렬 반환
 - 1로 채워짐

In [13]:
print np.ones((3, 3, 2)) # 3x2 행렬이 3개 생긴다. 
print
print np.ones(3)

[[[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]]

[ 1.  1.  1.]


In [11]:
print np.ones((4,4))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [17]:
print np.random.rand(3) # rand는 [0, 1) 사이에서. 지금 3개 출력하라는 명령 줬음.
print np.random.randn(3) # randn은 정규분포. 

[ 0.10256794  0.03815951  0.44983344]
[ 0.82081208 -0.20752858 -1.15797069]


In [16]:
print np.random.rand(3)
print np.random.randn(3)

[ 0.3193874   0.60321769  0.85021375]
[ 1.63949048  0.41172886 -0.95866112]


In [29]:
np.random.seed(0) #랜덤한 값을 계속 유지하고 싶을 때 사용
print np.random.rand()

0.548813503927


In [25]:
np.random.seed(10)
print np.random.rand(3)

[ 0.77132064  0.02075195  0.63364823]


* slicing
 - 리스트, 문자열 slicing과 동일함

In [32]:
arr1 = np.array([1, 3, 4, 6])
print arr1[0]
print arr1[1:-1]

1
[3 4]


In [30]:
arr1 = np.array([1,4,7,10, 12])
print arr1[1:3]
print arr1[1:-1]

[4 7]
[ 4  7 10]


In [36]:
arr2 = np.array([[0, 1, 3], [2, 4, 6]])

print arr2[0]
print arr2[0, 1]
print arr2[1:, :2] # 1행이니까 2,4,6. 마지막 열 제거. 둘다 범위가 들어갔으니 범위 유지하면서 2차원으로 출력됨. 
print arr2[:, 2]
print arr2[:, 1:]


[0 1 3]
1
[[2 4]]
[3 6]
[[1 3]
 [4 6]]


In [35]:
arr2 = np.array([[1,2,3], [2,6,10], [3,5,7]]) # [[], []] 이해하지?
print arr2[1,1]
print arr2[1:, :2]

6
[[2 6]
 [3 5]]


* array masking
  - numpy의 원소를 선택하거나 제거하여 추출하는 방법

In [4]:
arr = np.random.randint(0, 35, 10) #이 범위에서 10개 가져와라.
print arr #ndarray

[14 31  0 15 17  9 29 19 12 21]


In [41]:
arr = np.random.randint(0,10,3)
print arr

[8 4 1]


In [5]:
even_mask = (arr % 2 == 0) #numpy에서는 ndarray에 연산을 해버리면 원소 일일히 다 연산이 됨.
print even_mask
print 
print arr[even_mask] #True인 것만 가져온다
print
print arr[arr % 2 == 0]

[ True False  True False False False False False  True False]

[14  0 12]

[14  0 12]


In [56]:
arr = np.random.randint(0, 100, 10)
even_masking = (arr % 2 == 0)
print even_masking
print arr[even_masking] #true인것만 가져와서 array만듬
print arr[arr % 2 ==0]

[False  True False False False  True False False  True  True]
[ 2 52 84 48]
[ 2 52 84 48]


* operations
  - 기본 연산은 벡터화되어 전체 원소에 적용된다.
  - 벡터화: 한번에 해버려!

In [60]:
arr = np.arange(1, 7) * 5
print arr

[ 5 10 15 20 25 30]


In [62]:
arr2 = np.arange(1,5) ** 3
print arr2
print arr2 ** 0.5

[ 1  8 27 64]
[ 1.          2.82842712  5.19615242  8.        ]


In [58]:
arr1 = np.arange(0, 30, 3) + 3
arr2 = np.arange(1, 11)
print arr1, arr2
print
print arr1 - arr2 
print arr1 * arr2 #길이가 다르면 이건 계산 안되.


[ 3  6  9 12 15 18 21 24 27 30] [ 1  2  3  4  5  6  7  8  9 10]

[ 2  4  6  8 10 12 14 16 18 20]
[  3  12  27  48  75 108 147 192 243 300]


In [39]:
#XoR

print 4^2 #110, 10에서 다르면 1 같으면 0

6


In [66]:
arr1 = np.array([[1, 1], [1, 1]])
arr2 = np.array([[2, 2], [2, 2]])

print arr1 * arr2  # 원소끼리의 곱
print
print arr1.dot(arr2) # 행렬 곱

[[2 2]
 [2 2]]

[[4 4]
 [4 4]]


* logical operator 
  - all(), any()

In [86]:
arr = np.random.randint(1, 10, size = (4,4)) #앞서 해봤듯이 tuple를 통해 행렬 size 지정할 수 있음
print arr

[[7 6 8 4]
 [8 1 4 7]
 [1 8 3 6]
 [2 1 3 4]]


In [87]:
print np.all(arr < 10) #모든 원소가 조건을 만족시키면 True반환
print np.all(arr < 10)

True
True


In [88]:
print np.any(arr % 7 == 0) #1개의 원소라도 조건을 만족시키면 True반환
print np.any(arr % 5 == 0 )

True
False


* ravel
  - 다차원배열을 1차원으로 늘이기

In [89]:
arr = np.array([np.arange(1, 6), np.arange(10, 15)])
print arr
print
print arr.ravel() #1차원으로 보내버림.

[[ 1  2  3  4  5]
 [10 11 12 13 14]]

[ 1  2  3  4  5 10 11 12 13 14]


In [98]:
arr = np.array([np.arange(1,6), np.arange(10,15)])
print arr
print arr.ravel()
print arr.ravel().reshape(5,2)

[[ 1  2  3  4  5]
 [10 11 12 13 14]]
[ 1  2  3  4  5 10 11 12 13 14]
[[ 1  2]
 [ 3  4]
 [ 5 10]
 [11 12]
 [13 14]]


* reshaping
 - array의 shape을 재정렬

In [92]:
arr = np.arange(1, 16)
print arr
print
arr2 = arr.reshape(3, 5) #row, column 갯수 지정
print arr2
print
print arr2.ravel()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


* 자주 쓰는 numpy 함수

In [106]:
arr = np.arange(1, 16)

print arr
print np.min(arr)
print np.max(arr)
print np.mean(arr)
print np.median(arr)
print np.std(arr)
print np.argmin(arr) #최소값의 인덱스 반환
print np.argmax(arr) #최대값의 인덱스 반환
print np.sum(arr)
print np.sqrt(arr) #각 원소별로 구함.
print
lst = range(10,16)
print lst
print np.mean(lst) #list에서도 쓸 수 있음.
print np.sqrt(lst) #근데 값은 array로 반환함

A =  [[2, 3, 4], [1, 2, 3]]
B =  [[2, 3], [1, 2], [3, 4]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1
15
8.0
8.0
4.32049379894
0
14
120
[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766  3.31662479  3.46410162
  3.60555128  3.74165739  3.87298335]

[10, 11, 12, 13, 14, 15]
12.5
[ 3.16227766  3.31662479  3.46410162  3.60555128  3.74165739  3.87298335]


* 연습문제)
1. numpy를 이용하여 Math.pi 값을 다시 구해봅시다.
2. python 기본 리스트 객체로 만든 두 행렬을 곱하는 코드를 작성하시오.

In [6]:
#1.
import numpy as np
number = 100000
x = np.random.rand(number)
y = np.random.rand(number)
z = x**2 + y**2
count = 0
for i in z:
    if i <= 1:
        count += 1
        
print 4 * (count/float(number))


3.1382


In [14]:
a = np.random.rand(5,2)
print a
print a**2
np.sum(a) #다 더하는 것.
np.sum(a, axis = 0) #행 따라가면서 더해라
np.sum(a, axis = 1) #열 따라가면서 더해라

[[ 0.49931798  0.82136635]
 [ 0.58634032  0.67444511]
 [ 0.5025245   0.97202871]
 [ 0.43896612  0.94436338]
 [ 0.58145476  0.752757  ]]
[[ 0.24931844  0.67464268]
 [ 0.34379497  0.45487621]
 [ 0.25253087  0.94483982]
 [ 0.19269125  0.89182219]
 [ 0.33808964  0.5666431 ]]


array([ 1.32068433,  1.26078543,  1.47455321,  1.38332949,  1.33421177])

In [33]:
import numpy as np
count = 10000
points = np.random.rand(count,2)
points_sum = np.sum(points ** 2, axis = 1)
print (points_sum<=1.0) #True는 값으로 치면 1
pi = np.sum(points_sum <= 1.0) / float(count)
print pi * 4

[ True False False ...,  True  True False]
3.1352


# numpy만으로 만들기! 더이상 loop 안쓰는 것을 지향하자. 이게 제일 중요.

In [28]:
count = 1000000
points = np.random.rand(count, 2)
points_sum = np.sum(points**2, axis = 1) #제곱한 어레이를 열을 따라가면서 더함. 즉 x**2 + y**2 가 원소로 있는 세로로 기다란 어레이가 됨
p = np.sum(points_sum<=1.0)/float(count) #True면 값은 1
print p * 4

3.14084


In [27]:
#2. python 기본 리스트 객체로 만든 두 행렬을 곱하는 코드를 작성하시오.
a = [[1, 2, 3], [2, 3, 4]]
b = [[2, 3], [4, 5], [6, 7]]

l = len(b[0])
n = len(b)
m = len(a)

result = []

for j in range(m):
    for k in range(l):
        total = 0
        for i in range(n):
            total += a[j][i] * b[i][k]
        result.append(total)

print result

[28, 34, 40, 49]


* pandas basic
  - http://pandas.pydata.org/
  - Opensource python 고성능 데이터 분석 라이브러리
  - numpy기반
  - DataFrame(excel과 유사), Series 객체가 가장 많이 사용.
  - ML library인 scikit-learn과 함께 ML 분석에 많이 사용 됨
  - pip install pandas로 설치
  
  
* 아나콘다
 - venv랑 충돌을 일으키므로 같이 사용하기 힘듬

In [108]:
import numpy as np
import pandas as pd

 * Series
  - pandas의 기본 객체 중 하나
  - numpy의 ndarray를 기반으로 인덱싱을 기능을 추가하여 1차원 배열을 나타냄
  - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성
  - 같은 타입의 0개 이상의 데이터를 가질 수 있음
  - 인덱스를 지정할 수 있음.

In [118]:
s1 = pd.Series(20)
print s1 #인덱스랑 데이터 출력. 아무것도 지정안해서 디폴트로 인덱스가 숫자로 나옴


s2 = pd.Series(("A", 1))
print s2

0    20
dtype: int64
0    A
1    1
dtype: object


In [58]:
print s1[0] #인덱스로 접근

20


In [117]:
s2 = pd.Series(range(1,6)) #range는 datatype이 int64
print s2
s3 = pd.Series(np.arange(1,8)) #np.arange는 datatype이 int32
print s3

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32


 * 값 및 인덱스 접근
  - 각가 values, index 속성

In [126]:
s2 = pd.Series(range(1,6)) #range는 datatype이 int64
print s2
print s2.values

0    1
1    2
2    3
3    4
4    5
dtype: int64
[1 2 3 4 5]


In [127]:
print s2.index #stop은 포함 안함.


RangeIndex(start=0, stop=5, step=1)
a    1
b    2
c    3
d    4
e    5
dtype: int64
Index([u'a', u'b', u'c', u'd', u'e'], dtype='object')


* index 지정하기

In [159]:
s3 = pd.Series(range(1,6), index = ["a", "b","c","d","e"])
print s3.values
print s3.index

[1 2 3 4 5]
Index([u'a', u'b', u'c', u'd', u'e'], dtype='object')


In [137]:
print s3[1] # 기본 인덱스를 지정한 후에도 0based index로도 접근가능. 단 숫자로 index를 지정하면 0based인덱스는 사용못함
print s3['c'] 
print s3[2]

2
3
3


* index 재사용

In [138]:
s4 = pd.Series(2, index = s3.index)
print s4

s5 = pd.Series(range(5,10), index = s3.index)
print s5

a    2
b    2
c    2
d    2
e    2
dtype: int64
a    5
b    6
c    7
d    8
e    9
dtype: int64


In [147]:
s5 = pd.Series(np.random.randn(5)) #numpy.random.radnn: Return a sample (or samples) from the “standard normal” distribution.
print s5

0   -0.471400
1    0.349476
2    1.611457
3    0.239339
4    0.485003
dtype: float64


In [20]:
s6 = pd.Series(np.arange(1, 9))
print s6

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int32


In [74]:
s7 = pd.Series({'a' : 100, 'b' : 1000, 'c' : 2, 'd' : 6})
print s7
print
print s7['b']

a     100
b    1000
c       2
d       6
dtype: int64

1000


* Series size, shape, unique, count

In [154]:
s = pd.Series([0, 1, 1, 2, 3, 4, 5, 6, 7, np.nan]) #nan = not a number
print s

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64


In [155]:
print len(s)

10


In [156]:
print s.size

10


In [160]:
print s.shape #return a tuple of the shape of the underlying data
print s3.shape

(10,)
(5,)


In [161]:
print s.count() # NaN을 제외한 값을 카운팅

9


In [163]:
print s.unique() #중복된 것 제외하고 가져옴. NaN도 포함됨.

[  0.   1.   2.   3.   4.   5.   6.   7.  nan]


In [164]:
print s.value_counts() # NaN 제외하고 값들을 카운팅하고 series 반환. 카운팅의 대상이 key가 되고, 빈도가 value가 된다. 

#dtype: int64 의 의미는? 
""""""

1.0    2
7.0    1
6.0    1
5.0    1
4.0    1
3.0    1
2.0    1
0.0    1
dtype: int64


''

* head, tail, take

In [84]:
s.head() # 상위 5개 출력

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
dtype: float64

In [85]:
s.head(n = 3)

0    0.0
1    1.0
2    1.0
dtype: float64

In [86]:
s.tail()

5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64

In [87]:
s.tail(n = 2)

8    7.0
9    NaN
dtype: float64

In [167]:
print s
print 
print s.take([0, 4, 3, 9]) #지정한 인덱스의 series가져와서 반환

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64

0    0.0
4    3.0
3    2.0
9    NaN
dtype: float64


In [169]:
s = pd.Series(np.arange(1, 4), index = ['x', 'y', 'z'])
print s
s.take([0, 2])
#s.take(['x', 'z']) #0 - based index만 가능

x    1
y    2
z    3
dtype: int32


x    1
z    3
dtype: int32

* 값 접근하기

 * single value

In [34]:
print s['x']

1


In [175]:
print s[1]
print s3["a"] #내가 지정한 인덱스로도 접근 가능하고
print s3[0]#인덱스를 지정했더라도 0based 인덱스로도 접근가능하고

2
1
1


* multiple values

In [176]:
print s[['x', 'z']] #밖에 있는 []로 인덱스에 접근하는 것. 안에 있는 []리스트 표현

x    1
z    3
dtype: int32


In [177]:
s = pd.Series([1, 2, 3], index = [100, 101, 102])
print s

100    1
101    2
102    3
dtype: int64


* loc , iloc
  - loc[] : index
  - iloc[] : 0 based index

In [38]:
print s.loc[100] #loc: location. 내가 명시한 index로 접근해서 가져옴. dataframe에서 많이 씀!

1


In [96]:
print s.iloc[0] #얘는 0based index로 접근.

1


In [101]:
print s.loc[[100, 102]] #이것도 series로 반환. 한개만 주면 값만 나오고, 여러개주면 series로 반환

100    1
102    3
dtype: int64


In [102]:
print s.iloc[[0, 2]] #iloc: integer location

100    1
102    3
dtype: int64


In [104]:
s.loc[[100, 102, 104, 105]] #102까지 밖에 없는데 반환하라고 하니까 NaN반환

100    1.0
102    3.0
104    NaN
105    NaN
dtype: float64

In [183]:
s11 = pd.Series(range(1,7))
print s11
s11.iloc[[0, 2, 1, 5, 4]]

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


0    1
2    3
1    2
5    6
4    5
dtype: int64

* index를 기준으로 더하기

In [4]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
print s1

a    1
b    2
c    3
d    4
dtype: int64


In [5]:
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])
s2

d    4
c    3
b    2
a    1
dtype: int64

In [190]:
print s1 + s2 #인덱스 기준으로!

a    2
b    4
c    6
d    8
dtype: int64


In [191]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])
a1 + a2

array([5, 5, 5, 5])

* 산술연산

In [192]:
print s1
print s1 ** 2 #원소마다 연산한 결과가 나오고
print s1 #저장되진 않는다.

a    1
b    2
c    3
d    4
dtype: int64
a     1
b     4
c     9
d    16
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [196]:
exp = pd.Series(2, s1.index) 
print exp
print s1 ** exp
print s11
exp = pd.Series(2, index = range(6)) 
print s11 ** exp

a    2
b    2
c    2
d    2
dtype: int64
a     1
b     4
c     9
d    16
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0     1
1     4
2     9
3    16
4    25
5    36
dtype: int64


In [197]:
s1 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 5})
s2 = pd.Series({'b': 6, 'c': 7, 'd': 9, 'e': 10})

print s1 + s2
#한 쪽에만 있는 값은 NaN나옴!

a     NaN
b     8.0
c    10.0
d    14.0
e     NaN
dtype: float64


* NaN
  - numpy와 비교

In [8]:
nda = np.array([1, 2, 3, 4, 5])
print nda
print nda.mean()
print np.mean(nda)#수학적 라이브러리

[1 2 3 4 5]
3.0
3.0


In [119]:
nda = np.array([1, 2, 3, 4, np.NaN])
print nda.mean() #numpy 이용했을 때는 nan

nan


In [9]:
s = pd.Series([1, 2, 3, 4, np.NaN])
print s
print
print s.mean() #pandas 이용했을 때는 nan제외하고 계산
print s.mean(skipna=False) #데이터 분석 라이브러리.

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

2.5
nan


 * **Boolean selection**
  - **boolean Series가 []와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함됨**
  - boolean으로 조건을 주면 True인 것만 가져온다.

In [204]:
s = pd.Series(np.arange(1, 10))#np ndarray로부터 만들었다.
print s
print s > 5 # 이 조건을 만족하는 것들은 다 True.
# 6부터 True.
print s[s>5] #True인 것만 값으로 반환한다.

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32
0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool
5    6
6    7
7    8
8    9
dtype: int32


In [205]:
my_logic = s > 5
print my_logic
print s[my_logic]

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool
5    6
6    7
7    8
8    9
dtype: int32


In [206]:
print s[s > 5]

5    6
6    7
7    8
8    9
dtype: int32


In [210]:
#print s > 5 and s < 8   #파이썬에서 원래 되는데 numpy, pandas에서 안됨.
#print s[s > 5 and s < 8]
print s[(s > 5) & (s < 8)] # & and , | or
print s[5<s<8] #이거 안되

5    6
6    7
dtype: int32


ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [214]:
print s
print (s >= 0).all()
print (s >= 2).all()

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32
True
False


In [8]:
print (s < 2).any() #s.any() Returns whether any element is True over requested axis
print s[s < 2].any()

True
True


In [218]:
print s
print s[s>=7]
print
print s[s >= 7].sum() #7,8,9
print (s >= 7).sum() #1,1,1 왜냐하면 True이므로

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32
6    7
7    8
8    9
dtype: int32

24
3


* Series 값 변경
 - mutable

In [131]:
s = pd.Series([1, 10, 100], index = ['a', 'b', 'c'])
s['d'] = 1000

print s

s['d'] = 10000
print s

a       1
b      10
c     100
d    1000
dtype: int64
a        1
b       10
c      100
d    10000
dtype: int64


In [222]:
s1 = pd.Series(range(6))
s1[0] = 1
s1[9] = 5
print s1

0    1
1    1
2    2
3    3
4    4
5    5
9    5
dtype: int64


In [291]:
del s['a']
print s

b       10
c      100
d    10000
dtype: int64


* Slicing

In [226]:
s = pd.Series(np.arange(100, 110), index=np.arange(10, 20))
print s[0:5] #slicing은 0based
print
print s[:5] 
print
print s[5:]
print 
print s[-3:]

10    100
11    101
12    102
13    103
14    104
dtype: int32

10    100
11    101
12    102
13    103
14    104
dtype: int32

15    105
16    106
17    107
18    108
19    109
dtype: int32

17    107
18    108
19    109
dtype: int32


In [231]:
s.value_counts() # Returns object containing counts of unique values..   series에서 이것만 거의 많이씀. 그런데 왜 거꾸로 읽는거지?

109    1
108    1
107    1
106    1
105    1
104    1
103    1
102    1
101    1
100    1
dtype: int64

* DataFrame
  - Series가 1차원이라면 DataFrame은 2차원으로 확대된 버젼
  - Excel spreadsheet이라고 생각하면 이해하기 쉬움
  - 2차원이기 때문에 인덱스가 row, column로 구성됨. table!

In [232]:
import numpy as np
import pandas as pd

In [234]:
df = pd.DataFrame(np.array([[10, 11], [20, 22]])) #2차원 배열을 넣어줌.
print df

    0   1
0  10  11
1  20  22


* shape

In [237]:
df1 = pd.DataFrame([pd.Series(np.arange(10, 15)) ,
            pd.Series(np.arange(20, 25))])
print df1
print
print 
print df1.shape #tuple이겠지 행,열 반환이니까. (행,열)
print
print df1.info()
print
print df1.describe() #중요. 딱 데이터를 처음 받으면 많이 호출하는게 head랑 describe
#행은 데이터, 열은 속성. 그러니 decribe같은 경우는 각 속성에 대해서 알려주는 것.

    0   1   2   3   4
0  10  11  12  13  14
1  20  21  22  23  24


(2, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
0    2 non-null int32
1    2 non-null int32
2    2 non-null int32
3    2 non-null int32
4    2 non-null int32
dtypes: int32(5)
memory usage: 76.0 bytes
None

               0          1          2          3          4
count   2.000000   2.000000   2.000000   2.000000   2.000000
mean   15.000000  16.000000  17.000000  18.000000  19.000000
std     7.071068   7.071068   7.071068   7.071068   7.071068
min    10.000000  11.000000  12.000000  13.000000  14.000000
25%    12.500000  13.500000  14.500000  15.500000  16.500000
50%    15.000000  16.000000  17.000000  18.000000  19.000000
75%    17.500000  18.500000  19.500000  20.500000  21.500000
max    20.000000  21.000000  22.000000  23.000000  24.000000


In [146]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), columns = ['a', 'b'])
print df
print
print df.columns
print
print df.columns[0], df.columns[1] #열은 리스트니까 이렇게 출력 가능
print
df.columns = ['t1', 't2'] #column이름 변경 가능.
print df

    a   b
0  10  20
1  20  30

Index([u'a', u'b'], dtype='object')

a b

   t1  t2
0  10  20
1  20  30


In [147]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), columns = ['a', 'b'], index = ['d1', 'd2']) #rows가 아니라 index로 지정함.
print df
print df.index

     a   b
d1  10  20
d2  20  30
Index([u'd1', u'd2'], dtype='object')


* Series dictionary로 부터 생성

In [149]:
s1 = pd.Series(np.arange(1, 6, 1))
s2 = pd.Series(np.arange(6, 11, 1))
df = pd.DataFrame({'c1': s1, 'c2': s2})

print df

   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10


# file이름만 주면 내용 전부 읽어옴.

In [247]:
sample_df = pd.read_csv('sample.csv',  usecols = [0, 1, 2, 3, 7]) 
#sample_df = pd.read_csv('sample.csv')  usecols지정 안하면 전부 불러들임
print sample_df.head() #그런데 symbol은 유니크하니까 이걸 인덱스로 사용할 수도 있겠지. 그렇게 하려면 index_col을 symbol로 지정하면됨.
print
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', usecols = [0, 1, 2, 3, 7]) #데이터 분석의 시작은 read csv. usecols로 내가 가져올 칼럼 정함.
print sample_df.head()
print
print sample_df[['Price']].mean()

  Symbol                 Name                  Sector   Price  Book Value
0    MMM           3M Company             Industrials  177.12       19.34
1    ABT  Abbott Laboratories             Health Care   41.89       14.10
2   ABBV               AbbVie             Health Care   64.16        2.87
3    ACN        Accenture plc  Information Technology  115.11       11.45
4   ATVI  Activision Blizzard  Information Technology   41.29       11.31

                       Name                  Sector   Price  Book Value
Symbol                                                                 
MMM              3M Company             Industrials  177.12       19.34
ABT     Abbott Laboratories             Health Care   41.89       14.10
ABBV                 AbbVie             Health Care   64.16        2.87
ACN           Accenture plc  Information Technology  115.11       11.45
ATVI    Activision Blizzard  Information Technology   41.29       11.31

Price    86.044306
dtype: float64


In [300]:
print len(sample_df)

504


In [301]:
print sample_df.index #앞에서 symbols를 인덱스로 주었지.
print 
print sample_df.columns

Index([u'MMM', u'ABT', u'ABBV', u'ACN', u'ATVI', u'AYI', u'ADBE', u'AAP',
       u'AES', u'AET',
       ...
       u'XEL', u'XRX', u'XLNX', u'XL', u'XYL', u'YHOO', u'YUM', u'ZBH',
       u'ZION', u'ZTS'],
      dtype='object', name=u'Symbol', length=504)

Index([u'Name', u'Sector', u'Price', u'Book Value'], dtype='object')


In [253]:
#apple_df = pd.read_csv('apple.csv', header = None)
apple_df = pd.read_csv('apple.csv')
print apple_df[:10] # 이건 row를 선택해서 가져옴! 다만 slicing만 지원하고 [8] 같은 특정 indexing은 지원 안함.

        Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412
4  26-Sep-16  111.64  113.39  111.55  112.88  29869442
5  23-Sep-16  114.42  114.79  111.55  112.71  52481151
6  22-Sep-16  114.35  114.94  114.00  114.62  31073984
7  21-Sep-16  113.85  113.99  112.44  113.55  36003185
8  20-Sep-16  113.05  114.12  112.51  113.57  34514269
9  19-Sep-16  115.19  116.18  113.25  113.58  47023046


* column 선택하기

In [255]:
print apple_df[[0, 4, 5]] #0,4,5번째 컬럼을 가져옴. []안에 쓰면 인덱스로 받아들이므로, [[]] 안에 column지정해줘야함

         Date   Close     Volume
0   30-Sep-16  113.05   36379106
1   29-Sep-16  112.18   35886990
2   28-Sep-16  113.95   29641085
3   27-Sep-16  113.09   24607412
4   26-Sep-16  112.88   29869442
5   23-Sep-16  112.71   52481151
6   22-Sep-16  114.62   31073984
7   21-Sep-16  113.55   36003185
8   20-Sep-16  113.57   34514269
9   19-Sep-16  113.58   47023046
10  16-Sep-16  114.92   79886911
11  15-Sep-16  115.57   90613177
12  14-Sep-16  111.77  112340318
13  13-Sep-16  107.95   62176190
14  12-Sep-16  105.44   45292770
15   9-Sep-16  103.13   46556984
16   8-Sep-16  105.52   53002026
17   7-Sep-16  108.36   42364328
18   6-Sep-16  107.70   26880391
19   2-Sep-16  107.73   26334858
20   1-Sep-16  106.73   26701523


In [256]:
print type(apple_df[[0, 4, 5]])
print type(apple_df[[0]]) #한개만 주기 위해서 []사용.
print type(apple_df[['Date']])
print type(apple_df[['Date', 'Close']])
print type(apple_df['Date']) #컬럼에 이름으로만 줄 때는 한개만 줌. 시리즈로 반환

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [257]:
print apple_df.Date
print apple_df.Close #이렇게 특정 칼럼 값들만 출력 가능

0     30-Sep-16
1     29-Sep-16
2     28-Sep-16
3     27-Sep-16
4     26-Sep-16
5     23-Sep-16
6     22-Sep-16
7     21-Sep-16
8     20-Sep-16
9     19-Sep-16
10    16-Sep-16
11    15-Sep-16
12    14-Sep-16
13    13-Sep-16
14    12-Sep-16
15     9-Sep-16
16     8-Sep-16
17     7-Sep-16
18     6-Sep-16
19     2-Sep-16
20     1-Sep-16
Name: Date, dtype: object
0     113.05
1     112.18
2     113.95
3     113.09
4     112.88
5     112.71
6     114.62
7     113.55
8     113.57
9     113.58
10    114.92
11    115.57
12    111.77
13    107.95
14    105.44
15    103.13
16    105.52
17    108.36
18    107.70
19    107.73
20    106.73
Name: Close, dtype: float64


* row 선택하기
  - Seires의 경우 []로 row 선택이 가능하나, DataFrame의 경우는 기본적으로 column을 선택하도록 설계
  - [:10]과 같이 slicing의 경우에는 row 선택 가능
  - .loc, .iloc, .ix 의 함수로 row 선택 가능 .ix는 loc, iloc기능 둘다 지원

In [310]:
print apple_df[:10]

        Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412
4  26-Sep-16  111.64  113.39  111.55  112.88  29869442
5  23-Sep-16  114.42  114.79  111.55  112.71  52481151
6  22-Sep-16  114.35  114.94  114.00  114.62  31073984
7  21-Sep-16  113.85  113.99  112.44  113.55  36003185
8  20-Sep-16  113.05  114.12  112.51  113.57  34514269
9  19-Sep-16  115.19  116.18  113.25  113.58  47023046


In [261]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', usecols = [0, 1, 2, 3, 7])
print sample_df['MMM' : 'ACN'] #문자열로 표시할 때는 마지막꺼도 포함. 숫자와 다르게.

                       Name                  Sector   Price  Book Value
Symbol                                                                 
MMM              3M Company             Industrials  177.12       19.34
ABT     Abbott Laboratories             Health Care   41.89       14.10
ABBV                 AbbVie             Health Care   64.16        2.87
ACN           Accenture plc  Information Technology  115.11       11.45


In [267]:
print sample_df.loc['MMM'] #loc을 쓰니까 row를 가져오겠다는 의지를 보인 것. loc이 없으면 column에 MMM없으니까 error.
print
print sample_df.iloc[0]

Name           3M Company
Sector        Industrials
Price              177.12
Book Value          19.34
Name: MMM, dtype: object

Name           3M Company
Sector        Industrials
Price              177.12
Book Value          19.34
Name: MMM, dtype: object


In [274]:
print sample_df.loc[['MMM', 'MSFT']]
print
print sample_df.iloc[0,2] #여기서 출력되는 값은 뭐지???
print sample_df.iloc[[0,2]]

                   Name                  Sector   Price  Book Value
Symbol                                                             
MMM          3M Company             Industrials  177.12       19.34
MSFT    Microsoft Corp.  Information Technology   52.30        9.51

177.12
              Name       Sector   Price  Book Value
Symbol                                             
MMM     3M Company  Industrials  177.12       19.34
ABBV        AbbVie  Health Care   64.16        2.87


In [271]:
print sample_df.iloc[[0, 1, 2]]
print type(sample_df.iloc[[0, 1, 2]])

print sample_df.iloc[0] 
print type(sample_df.iloc[0])

                       Name       Sector   Price  Book Value
Symbol                                                      
MMM              3M Company  Industrials  177.12       19.34
ABT     Abbott Laboratories  Health Care   41.89       14.10
ABBV                 AbbVie  Health Care   64.16        2.87
<class 'pandas.core.frame.DataFrame'>
Name           3M Company
Sector        Industrials
Price              177.12
Book Value          19.34
Name: MMM, dtype: object
<class 'pandas.core.series.Series'>


In [60]:
print sample_df.ix[['MSFT', 'ZTS']] #ix는 문자로든 숫자로든 인덱스 뭐든 줄 수 있음. 콜론(:)도 사용할 수 있고. 그래서 많이 쓰임

                   Name                  Sector  Price  Book Value
Symbol                                                            
MSFT    Microsoft Corp.  Information Technology   52.3        9.51
ZTS              Zoetis             Health Care   48.5        2.35


In [61]:
print sample_df.ix[[10, 11, 12, 15]]

                                 Name       Sector   Price  Book Value
Symbol                                                                
AMG     Affiliated Managers Group Inc   Financials  138.85       53.30
AFL                         AFLAC Inc   Financials   72.49       48.22
A            Agilent Technologies Inc  Health Care   45.48       12.79
ALK              Alaska Air Group Inc  Industrials   59.86       19.81


* boolean selection으로 row 선택하기

In [278]:
print sample_df.Price > 100 #이 조건에 대해 series로 T,F반환

Symbol
MMM       True
ABT      False
ABBV     False
ACN       True
ATVI     False
AYI       True
ADBE     False
AAP       True
AES      False
AET       True
AMG       True
AFL      False
A        False
APD       True
AKAM     False
ALK      False
ALB      False
AA       False
ALXN      True
ALLE     False
AGN       True
ADS       True
LNT      False
ALL      False
GOOGL     True
GOOG      True
MO       False
AMZN      True
AEE      False
AAL      False
         ...  
V        False
VNO       True
VMC       True
WMT      False
WBA      False
WM       False
WAT       True
WFC      False
HCN      False
WDC      False
WU       False
WRK      False
WY       False
WHR       True
WFM      False
WMB      False
WLTW      True
WEC      False
WYN      False
WYNN     False
XEL      False
XRX      False
XLNX     False
XL       False
XYL      False
YHOO     False
YUM      False
ZBH       True
ZION     False
ZTS      False
Name: Price, dtype: bool


In [71]:
print sample_df[sample_df.Price > 100][['Price']] #True인 것들만 값 반환. 타겟 조건을 다시 타겟 시리즈에 넣어줌.

         Price
Symbol        
MMM     177.12
ACN     115.11
AYI     264.62
AAP     164.85
AET     117.00
AMG     138.85
APD     144.35
ALXN    124.42
AGN     240.59
ADS     200.96
GOOGL   717.78
GOOG    705.63
AMZN    745.81
AMT     113.66
AMGN    161.10
ANTM    132.15
AON     109.57
AZO     815.02
AVGO    155.14
AVB     184.94
BCR     239.00
BDX     175.64
BRK-B   143.65
BIIB    251.30
BLK     345.20
BA      130.09
BXP     133.32
CELG    105.03
CVX     104.77
CMG     399.71
...        ...
RTN     138.49
REGN    378.35
ROK     115.70
ROP     170.04
SPGI    108.87
SRE     114.11
SHW     306.52
SPG     219.56
SLG     105.98
SJM     154.08
SNA     160.16
SWK     114.97
SRCL    104.70
SYK     122.29
CLX     138.37
HSY     110.70
TRV     118.08
TMO     152.69
TDG     269.81
ULTA    250.82
UNH     141.27
UPS     109.52
UTX     103.66
UHS     137.16
VNO     100.46
VMC     123.61
WAT     146.53
WHR     171.38
WLTW    125.06
ZBH     124.89

[122 rows x 1 columns]


* 새 column 추가하기

In [2]:
copy = sample_df.copy() #원본을 유지하기 위해 copy하고
copy['TwicePrice'] = sample_df.Price * 2
copy["TriplePrice"] = sample_df.Price * 3
copy.insert(4, "SquaredPrice", sample_df.Price **2)
print copy[:10]

NameError: name 'sample_df' is not defined

In [77]:
copy.insert(1, 'TriplePrice', sample_df.Price * 3) #맨 마지막에 들어가는게 싫어서 내가 원하는 위치에 넣기 위해서 insert함수 사용
print copy[:2]

                       Name  TriplePrice       Sector   Price  Book Value  \
Symbol                                                                      
MMM              3M Company       531.36  Industrials  177.12       19.34   
ABT     Abbott Laboratories       125.67  Health Care   41.89       14.10   

        TwicePrice  
Symbol              
MMM         354.24  
ABT          83.78  


 * column 삭제하기

In [78]:
print copy[:2]
del copy['Sector']
print copy[:2]

                       Name  TriplePrice       Sector   Price  Book Value  \
Symbol                                                                      
MMM              3M Company       531.36  Industrials  177.12       19.34   
ABT     Abbott Laboratories       125.67  Health Care   41.89       14.10   

        TwicePrice  
Symbol              
MMM         354.24  
ABT          83.78  
                       Name  TriplePrice   Price  Book Value  TwicePrice
Symbol                                                                  
MMM              3M Company       531.36  177.12       19.34      354.24
ABT     Abbott Laboratories       125.67   41.89       14.10       83.78


 * row 추가/삭제하기

In [3]:
df1 = copy.iloc[0:3].copy() #copy에서 [0:3]만큼 떼어와서 다시 copy
copy = copy.append(df1) #새로운 dataframe을 append하거나
print copy.tail()

copy.loc['Aaron'] = ['Aaron', 1000.0, 1000.0, 1000.0, 2000.0] #직접 값을 입력하면 됨
print copy.tail()
#그런데 row는 한개씩 추가할 일이 많이 없을 것. 

NameError: name 'copy' is not defined

In [84]:
copy = copy.drop(['Aaron']) #row 삭제할 때 drop
copy.tail()

Name  TriplePrice   Price  Book Value  TwicePrice
Symbol                                                                  
ABT     Abbott Laboratories       125.67   41.89       14.10       83.78
ABBV                 AbbVie       192.48   64.16        2.87      128.32
MMM              3M Company       531.36  177.12       19.34      354.24
ABT     Abbott Laboratories       125.67   41.89       14.10       83.78
ABBV                 AbbVie       192.48   64.16        2.87      128.32

In [284]:
selection = sample_df.Price > 200
lessthan200 = sample_df[-selection] # - 붙으면 반전. 즉  '<= 200'인 것만 나올 것.
print lessthan200[:3]

morethan200 = sample_df[selection]
print morethan200[:3]

                       Name       Sector   Price  Book Value
Symbol                                                      
MMM              3M Company  Industrials  177.12       19.34
ABT     Abbott Laboratories  Health Care   41.89       14.10
ABBV                 AbbVie  Health Care   64.16        2.87
                         Name                  Sector   Price  Book Value
Symbol                                                                   
AYI         Acuity Brands Inc             Industrials  264.62       36.50
AGN              Allergan plc             Health Care  240.59      183.41
ADS     Alliance Data Systems  Information Technology  200.96       29.51


## 데이터가 broad하면 알고리즘에 따른 차이가 크지 않음.
## 즉 잘 수집된 데이터는 설명력이 좋다.
## scikit learn은 single core기반이라 좀 떨어짐. 그래도 우리 수준에서 큰 무리 없음.