## numpy

In [10]:
import numpy as np

arr1 = np.array([[1,2,3], [2,3,4], [3,4,5]])
arr2 = np.array([[1,1,1], [1,1,1], [1,1,1]])

print arr1 + arr2
print arr1 * arr2


[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [18]:
arr3 = np.arange(1,10)
print(arr3)

print np.zeros((4,4))
print np.ones((4,4))

[1 2 3 4 5 6 7 8 9]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [41]:
print np.random.rand(2,2)
print
print np.random.randn(2,2)
print
print np.random.randint(2,4,5) #randint(low, high=None, size=None, dtype='l')


[[ 0.58891388  0.20189882]
 [ 0.70337127  0.21969226]]

[[ 1.55477274 -0.35452496]
 [-0.98796198 -0.07289024]]

[2 2 3 2 3]


In [57]:
arr4 = np.random.randn(4,4)
print arr4
print
print arr4[2: , 2:]

[[-1.02963517 -2.17220666 -0.11782192 -0.65497757]
 [-0.18953986 -0.0709924   0.42442585 -0.77893278]
 [-1.20560797  1.43956293  0.47724478 -0.06073908]
 [-0.502897    0.42428334  1.20344099  0.73430467]]

[[ 0.47724478 -0.06073908]
 [ 1.20344099  0.73430467]]


In [59]:
positive_mask = (arr4 > 0)
print positive_mask
print
print arr4[positive_mask]
print
print arr4[arr4 > 0]

[[False False False False]
 [False False  True False]
 [False  True  True False]
 [False  True  True  True]]

[ 0.42442585  1.43956293  0.47724478  0.42428334  1.20344099  0.73430467]

[ 0.42442585  1.43956293  0.47724478  0.42428334  1.20344099  0.73430467]


In [64]:
arr = np.arange(1,6) * 2
print arr

arr2 = np.arange(1,6)
print arr * arr2

[ 2  4  6  8 10]
[ 2  8 18 32 50]


In [65]:
import numpy as np

def mathPi(n):
    plots = np.random.rand(n, 2)
    plots_sum = np.sum(plots ** 2, axis = 1)
    plots_inside = np.sum(plots_sum <= 1)
    pi = 4 * plots_inside / float(n)
    return pi

print mathPi(10000)

3.1492


## pandas

In [16]:
import pandas as pd
import numpy as nd

s1 = pd.Series(("A","B"))
print s1
print s1[1]

s2 = pd.Series(range(1,11))
print s2.index

s3 = pd.Series(nd.arange(1,11))
print s3.values

s4 = pd.Series(range(1,11), index = ["A","B"]) #index와 values의 길이가 안맞아서 에러!

0    A
1    B
dtype: object
B
RangeIndex(start=0, stop=10, step=1)
[ 1  2  3  4  5  6  7  8  9 10]


ValueError: Wrong number of items passed 10, placement implies 2

In [21]:
s5 = pd.Series(range(1,5), index = ["a","b","c","d"])
print s5

s6 = pd.Series(range(11,15), index = s5.index)
print s6

s7 = pd.Series({"a": 100, "b": 97, "c": 86})
print s7

a    1
b    2
c    3
d    4
dtype: int64
a    11
b    12
c    13
d    14
dtype: int64
a    100
b     97
c     86
dtype: int64


In [33]:
import numpy as np
s = pd.Series([0,1,1,2,3,4,5,6,7,8,np.nan], index = range(1,12))
print s
print len(s), s.size
print s.shape
print s.count()
print s.unique()

1     0.0
2     1.0
3     1.0
4     2.0
5     3.0
6     4.0
7     5.0
8     6.0
9     7.0
10    8.0
11    NaN
dtype: float64
11 11
(11,)
10
[  0.   1.   2.   3.   4.   5.   6.   7.   8.  nan]


In [48]:
s = pd.Series([0,1,1,2,3,3,4,5,6,7,8,np.nan])
print s[[0,6,8]]

print s.iloc[[7,9]]
print s.iloc[range(7,10)]

0    0.0
6    4.0
8    6.0
dtype: float64
7    5.0
9    7.0
dtype: float64
7    5.0
8    6.0
9    7.0
dtype: float64


In [51]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([5,6,7,8])
print s1[[0,2]] + s2[[0,2]] # 짝지어서 계산되고
print s1[[0,2]] + s2[[1,3]] # NaN

0     6
2    10
dtype: int64
0   NaN
1   NaN
2   NaN
3   NaN
dtype: float64


In [53]:
exp = pd.Series(2, range(4))
print s1 ** 2
print s1 ** exp

0     1
1     4
2     9
3    16
dtype: int64
0     1
1     4
2     9
3    16
dtype: int64


In [57]:
s = pd.Series(np.arange(1,11))
print s
print s > 5
print s[s > 5]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32
0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
9     True
dtype: bool
5     6
6     7
7     8
8     9
9    10
dtype: int32


In [63]:
print (s > 5).all() # 모두 저 조건 만족해? False
print (s > 5).any() # 하나라도 저 조건 만족해? True
print (s > 5).sum()
print s[s > 5].sum() #두개가 뭐가 다른지 이젠 잘 알아야지~

False
True
5
40


In [1]:
s1 = pd.Series(range(1,11), range(1,11))
print s1
s1[11] = 11
print s1
del s1[7]
print s1

NameError: name 'pd' is not defined

In [2]:
import numpy as np
import pandas as pd

In [22]:
df = pd.DataFrame(np.array([[10,11],[12,13]]), columns = ["a", "b"] )
print df
print df.shape
df.info()
df.describe()
print
print df.columns[0], df.columns[1]
print df.index

s1 = pd.Series(np.arange(1,6))
s2 = pd.Series(np.arange(6,11))
df1 = pd.DataFrame({"c1": s1, "c2": s2})
print df1

    a   b
0  10  11
1  12  13
(2, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
a    2 non-null int32
b    2 non-null int32
dtypes: int32(2)
memory usage: 52.0 bytes

a b
RangeIndex(start=0, stop=2, step=1)
   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10


In [30]:
sample_df = pd.read_csv("sample.csv", index_col = "Symbol", usecols = [0,1,2,3,7])
print sample_df.head()
print
print sample_df["Price"].mean()
print len(sample_df)
print sample_df.index
print sample_df.columns

                       Name                  Sector   Price  Book Value
Symbol                                                                 
MMM              3M Company             Industrials  177.12       19.34
ABT     Abbott Laboratories             Health Care   41.89       14.10
ABBV                 AbbVie             Health Care   64.16        2.87
ACN           Accenture plc  Information Technology  115.11       11.45
ATVI    Activision Blizzard  Information Technology   41.29       11.31

86.0443055556
504
Index([u'MMM', u'ABT', u'ABBV', u'ACN', u'ATVI', u'AYI', u'ADBE', u'AAP',
       u'AES', u'AET',
       ...
       u'XEL', u'XRX', u'XLNX', u'XL', u'XYL', u'YHOO', u'YUM', u'ZBH',
       u'ZION', u'ZTS'],
      dtype='object', name=u'Symbol', length=504)
Index([u'Name', u'Sector', u'Price', u'Book Value'], dtype='object')


In [38]:
apple_df = pd.read_csv("apple.csv")
print apple_df.head()
print apple_df[[0,1,4]].head()
print apple_df[["Date", "Open", "Close"]].head()
print apple_df.Date.head() #이렇게 선택할 수도 있음.

        Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412
4  26-Sep-16  111.64  113.39  111.55  112.88  29869442
        Date    Open   Close
0  30-Sep-16  112.46  113.05
1  29-Sep-16  113.16  112.18
2  28-Sep-16  113.69  113.95
3  27-Sep-16  113.00  113.09
4  26-Sep-16  111.64  112.88
        Date    Open   Close
0  30-Sep-16  112.46  113.05
1  29-Sep-16  113.16  112.18
2  28-Sep-16  113.69  113.95
3  27-Sep-16  113.00  113.09
4  26-Sep-16  111.64  112.88
0    30-Sep-16
1    29-Sep-16
2    28-Sep-16
3    27-Sep-16
4    26-Sep-16
Name: Date, dtype: object


In [44]:
print apple_df[:5] #choose rows by index slicing 
print
print sample_df[3:10]

        Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412
4  26-Sep-16  111.64  113.39  111.55  112.88  29869442

                       Name                  Sector   Price  Book Value
Symbol                                                                 
ACN           Accenture plc  Information Technology  115.11       11.45
ATVI    Activision Blizzard  Information Technology   41.29       11.31
AYI       Acuity Brands Inc             Industrials  264.62       36.50
ADBE      Adobe Systems Inc  Information Technology   96.79       14.53
AAP      Advance Auto Parts  Consumer Discretionary  164.85       35.82
AES                AES Corp               Utilities   12.32        4.86
AET               Aetna Inc             Health Care  117.00       47.96


In [56]:
print sample_df.ix[3:9]
print
print sample_df.ix["AYI":"AAP"]
print
print sample_df[sample_df.Price > 300]
print
print sample_df[sample_df.Price > 300].Price

                       Name                  Sector   Price  Book Value
Symbol                                                                 
ACN           Accenture plc  Information Technology  115.11       11.45
ATVI    Activision Blizzard  Information Technology   41.29       11.31
AYI       Acuity Brands Inc             Industrials  264.62       36.50
ADBE      Adobe Systems Inc  Information Technology   96.79       14.53
AAP      Advance Auto Parts  Consumer Discretionary  164.85       35.82
AES                AES Corp               Utilities   12.32        4.86

                      Name                  Sector   Price  Book Value
Symbol                                                                
AYI      Acuity Brands Inc             Industrials  264.62       36.50
ADBE     Adobe Systems Inc  Information Technology   96.79       14.53
AAP     Advance Auto Parts  Consumer Discretionary  164.85       35.82

                           Name                  Sector    Price  B

In [99]:
copy = sample_df.copy()
copy["doublePrice"] = sample_df.Price  * 2
copy.insert(5, "triplePrice", sample_df.Price * 3)
print copy.head()

del copy["Sector"]
print copy.head()
print copy

                       Name                  Sector   Price  Book Value  \
Symbol                                                                    
MMM              3M Company             Industrials  177.12       19.34   
ABT     Abbott Laboratories             Health Care   41.89       14.10   
ABBV                 AbbVie             Health Care   64.16        2.87   
ACN           Accenture plc  Information Technology  115.11       11.45   
ATVI    Activision Blizzard  Information Technology   41.29       11.31   

        doublePrice  triplePrice  
Symbol                            
MMM          354.24       531.36  
ABT           83.78       125.67  
ABBV         128.32       192.48  
ACN          230.22       345.33  
ATVI          82.58       123.87  
                       Name   Price  Book Value  doublePrice  triplePrice
Symbol                                                                   
MMM              3M Company  177.12       19.34       354.24       531.36
ABT    

In [100]:
df1 = copy.iloc[0:3].copy()
print copy.tail()
copy = copy.append(df1)
print copy.tail()
print

copy.drop(["MMM"])
print copy.head() #drop은 저장을 해줘야해
copy = copy.drop(["MMM"])
print copy.head()

                          Name   Price  Book Value  doublePrice  triplePrice
Symbol                                                                      
YHOO                Yahoo Inc.   37.74       30.03        75.48       113.22
YUM            Yum! Brands Inc   85.76        0.38       171.52       257.28
ZBH     Zimmer Biomet Holdings  124.89       48.52       249.78       374.67
ZION             Zions Bancorp   24.74       33.23        49.48        74.22
ZTS                     Zoetis   48.50        2.35        97.00       145.50
                       Name   Price  Book Value  doublePrice  triplePrice
Symbol                                                                   
ZION          Zions Bancorp   24.74       33.23        49.48        74.22
ZTS                  Zoetis   48.50        2.35        97.00       145.50
MMM              3M Company  177.12       19.34       354.24       531.36
ABT     Abbott Laboratories   41.89       14.10        83.78       125.67
ABBV             

In [107]:
selection = sample_df.Price > 300
print sample_df[selection].head(10)
print
print sample_df[-selection].head(5)

                           Name                  Sector    Price  Book Value
Symbol                                                                      
GOOGL      Alphabet Inc Class A  Information Technology   717.78      179.92
GOOG       Alphabet Inc Class C  Information Technology   705.63      179.92
AMZN             Amazon.com Inc  Consumer Discretionary   745.81       31.26
AZO                AutoZone Inc  Consumer Discretionary   815.02      -63.16
BLK                   BlackRock              Financials   345.20      171.90
CMG      Chipotle Mexican Grill  Consumer Discretionary   399.71       52.48
EQIX                    Equinix  Information Technology   389.45       69.41
ISRG    Intuitive Surgical Inc.             Health Care   678.84      124.68
PCLN          Priceline.com Inc  Consumer Discretionary  1329.46      182.37
REGN                  Regeneron             Health Care   378.35       36.10

                       Name                  Sector   Price  Book Value
Sym